/* phxrpc_storesvr_stub.h

 Generated by phxrpc_pb2client from storesvr.proto

 Please DO NOT edit unless you know exactly what you are doing.

*/

#pragma once

#include "storesvr.pb.h"

namespace phxrpc {
    class BaseTcpStream;
    class ClientMonitor;
}

class StoresvrStub
{
public:
    StoresvrStub( phxrpc::BaseTcpStream & socket, phxrpc::ClientMonitor & client_monitor );
    ~StoresvrStub();

    void SetKeepAlive( const bool keep_alive );

    int PHXEcho( const google::protobuf::StringValue & req,
        google::protobuf::StringValue * resp );

    int GetRouterList( const storesvr::RouterReq & req,
        storesvr::RouterResp * resp );

    int GetSections( const storesvr::SectionReq & req,
        storesvr::SectionResp * resp );

    int storeSection( const storesvr::StoreReq & req,
        storesvr::StoreResp * resp );

private:
    phxrpc::BaseTcpStream & socket_;
    phxrpc::ClientMonitor & client_monitor_;
    bool keep_alive_;
};

