/* phxrpc_storesvr_service.h

 Generated by phxrpc_pb2service from storesvr.proto

 Please DO NOT edit unless you know exactly what you are doing.

*/

#pragma once

#include "storesvr.pb.h"

class StoresvrService
{
public:
    StoresvrService();
    virtual ~StoresvrService();

    virtual int PHXEcho( const google::protobuf::StringValue & req,
        google::protobuf::StringValue * resp );

    virtual int GetRouterList( const storesvr::RouterReq & req,
        storesvr::RouterResp * resp );

    virtual int GetSections( const storesvr::SectionReq & req,
        storesvr::SectionResp * resp );

    virtual int storeSection( const storesvr::StoreReq & req,
        storesvr::StoreResp * resp );

};

