/* phxrpc_storesvr_tool.h

 Generated by phxrpc_pb2tool from storesvr.proto

 Please DO NOT edit unless you know exactly what you are doing.

*/

#include <stdio.h>
#pragma once


namespace phxrpc {
    class OptMap;
}

class StoresvrTool
{
public:
    StoresvrTool();
    virtual ~StoresvrTool();

    virtual int PHXEcho( phxrpc::OptMap & bigmap );

    virtual int GetRouterList( phxrpc::OptMap & bigmap );

    virtual int GetSections( phxrpc::OptMap & bigmap );

    virtual int storeSection( phxrpc::OptMap & bigmap );

public:
    typedef int (StoresvrTool::*ToolFunc_t) ( phxrpc::OptMap & );

    typedef struct tagName2Func {
        const char * name;
        StoresvrTool::ToolFunc_t func;
        const char * opt_string;
        const char * usage;
    } Name2Func_t;

    static Name2Func_t * GetName2Func()
    {
        static Name2Func_t name2func [] = {
            { "PHXEcho", &StoresvrTool::PHXEcho, "c:f:vs:",
                    "-s <string>" },
            { "GetRouterList", &StoresvrTool::GetRouterList, "c:f:vv:",
                    "-v <router_ver>" },
            { "GetSections", &StoresvrTool::GetSections, "c:f:vs:",
                    "-s <sect_id1,sect_id2>" },
            { "storeSection", &StoresvrTool::storeSection, "c:f:vs:m:",
                    "-s <sect_id> -m <max_seq>" },
            { NULL, NULL }
        };

        return name2func;
    };
};

