/* phxrpc_storesvr_service.cpp

 Generated by phxrpc_pb2service from storesvr.proto

 Please DO NOT edit unless you know exactly what you are doing.

*/

#include "phxrpc_storesvr_service.h"
#include "storesvr.pb.h"
#include "phxrpc/file.h"

StoresvrService :: StoresvrService()
{
}

StoresvrService :: ~StoresvrService()
{
}

int StoresvrService :: PHXEcho( const google::protobuf::StringValue & /* req */,
        google::protobuf::StringValue * /* resp */ )
{
    phxrpc::log( LOG_ERR, "ERROR: PHXEcho unimplemented" );
    return -1;
}

int StoresvrService :: GetRouterList( const storesvr::RouterReq & /* req */,
        storesvr::RouterResp * /* resp */ )
{
    phxrpc::log( LOG_ERR, "ERROR: GetRouterList unimplemented" );
    return -1;
}

int StoresvrService :: GetSections( const storesvr::SectionReq & /* req */,
        storesvr::SectionResp * /* resp */ )
{
    phxrpc::log( LOG_ERR, "ERROR: GetSections unimplemented" );
    return -1;
}

int StoresvrService :: storeSection( const storesvr::StoreReq & /* req */,
        storesvr::StoreResp * /* resp */ )
{
    phxrpc::log( LOG_ERR, "ERROR: storeSection unimplemented" );
    return -1;
}


