/* phxrpc_storesvr_tool.cpp

 Generated by phxrpc_pb2tool from storesvr.proto

 Please DO NOT edit unless you know exactly what you are doing.

*/

#include "phxrpc/file.h"

#include "phxrpc_storesvr_tool.h"
#include "storesvr_client.h"

using namespace phxrpc;

StoresvrTool :: StoresvrTool()
{
}

StoresvrTool :: ~StoresvrTool()
{
}

int StoresvrTool :: PHXEcho( phxrpc::OptMap & /* opt_map */ )
{
   printf( "\n    *** PHXEcho unimplement ***\n" );

    return -1;
}

int StoresvrTool :: GetRouterList( phxrpc::OptMap & /* opt_map */ )
{
   printf( "\n    *** GetRouterList unimplement ***\n" );

    return -1;
}

int StoresvrTool :: GetSections( phxrpc::OptMap & /* opt_map */ )
{
   printf( "\n    *** GetSections unimplement ***\n" );

    return -1;
}

int StoresvrTool :: storeSection( phxrpc::OptMap & /* opt_map */ )
{
   printf( "\n    *** storeSection unimplement ***\n" );

    return -1;
}


