/* storesvr_tool_impl.h

 Generated by phxrpc_pb2tool from storesvr.proto

*/

#pragma once

#include <stdio.h>

#include "phxrpc_storesvr_tool.h"
namespace phxrpc {
    class OptMap;
}

class StoresvrToolImpl : public StoresvrTool
{
public:
    StoresvrToolImpl();
    virtual ~StoresvrToolImpl();

    virtual int PHXEcho( phxrpc::OptMap & opt_map );

    virtual int GetRouterList( phxrpc::OptMap & opt_map );

    virtual int GetSections( phxrpc::OptMap & opt_map );

    virtual int storeSection( phxrpc::OptMap & opt_map );

};

