/* storesvr_service_impl.h

 Generated by phxrpc_pb2service from storesvr.proto

*/

#pragma once

#include "storesvr.pb.h"
#include "phxrpc_storesvr_service.h"

class StoresvrServerConfig;

typedef struct tagServiceArgs {
    StoresvrServerConfig * config;
    //You can add other arguments here and initiate in main().
	uint64_t* store_mmap_;
	int store_file_;
}ServiceArgs_t;

class StoresvrServiceImpl : public StoresvrService
{
public:
    StoresvrServiceImpl( ServiceArgs_t & app_args );
    virtual ~StoresvrServiceImpl();

    virtual int PHXEcho( const google::protobuf::StringValue & req,
        google::protobuf::StringValue * resp );

    virtual int GetRouterList( const storesvr::RouterReq & req,
        storesvr::RouterResp * resp );

    virtual int GetSections( const storesvr::SectionReq & req,
        storesvr::SectionResp * resp );

    virtual int storeSection( const storesvr::StoreReq & req,
        storesvr::StoreResp * resp );

private:
    ServiceArgs_t & args_;

};

