/* storesvr_client.h

 Generated by phxrpc_pb2client from storesvr.proto

*/

#pragma once

#include "storesvr.pb.h"
#include "phxrpc/rpc.h"

class StoresvrClient
{
public:
    static bool Init( const char * config_file );

    static const char * GetPackageName();

public:
    StoresvrClient();
    ~StoresvrClient();

    int PHXEcho( const google::protobuf::StringValue & req,
        google::protobuf::StringValue * resp );

    int PhxBatchEcho( const google::protobuf::StringValue & req,
        google::protobuf::StringValue * resp );

    int GetRouterList( const storesvr::RouterReq & req,
        storesvr::RouterResp * resp );

    int GetSections( const storesvr::SectionReq & req,
        storesvr::SectionResp * resp );

    int storeSection( const storesvr::StoreReq & req,
        storesvr::StoreResp * resp );


};
