/* storesvr_server_config.cpp

 Generated by phxrpc_pb2server from storesvr.proto

*/

#include "storesvr.pb.h"
#include "storesvr_server_config.h"

StoresvrServerConfig :: StoresvrServerConfig()
{
}

StoresvrServerConfig :: ~StoresvrServerConfig()
{
}

bool StoresvrServerConfig :: Read( const char * config_file )
{
    bool ret = ep_server_config_.Read( config_file );

    if ( strlen( ep_server_config_.GetPackageName() ) == 0 ) {
        ep_server_config_.SetPackageName( 
storesvr::RouterReq::default_instance().GetDescriptor()->file()->package().c_str() );
    }

    return ret;
}

phxrpc::HshaServerConfig & StoresvrServerConfig :: GetHshaServerConfig()
{
    return ep_server_config_;
}
