/* allocsvr_service_impl.h

 Generated by phxrpc_pb2service from allocsvr.proto

*/

#pragma once

#include "allocsvr.pb.h"
#include "phxrpc_allocsvr_service.h"
#include "alloc_seq.h"

class AllocsvrServerConfig;

typedef struct tagServiceArgs {
    AllocsvrServerConfig * config;
    //You can add other arguments here and initiate in main().
}ServiceArgs_t;

class AllocsvrServiceImpl : public AllocsvrService
{
public:
    AllocsvrServiceImpl( ServiceArgs_t & app_args );
    virtual ~AllocsvrServiceImpl();

    virtual int PHXEcho( const google::protobuf::StringValue & req,
        google::protobuf::StringValue * resp );

    virtual int GetSeq( const allocsvr::SeqReq & req,
        allocsvr::SeqResp * resp );
private:
	void storeTimer();

private:
    ServiceArgs_t & args_;
};

