/* allocsvr_server_config.h

 Generated by phxrpc_pb2server from allocsvr.proto

*/

#pragma once

#include "phxrpc/rpc.h"

class AllocsvrServerConfig
{
public:
    AllocsvrServerConfig();

    ~AllocsvrServerConfig();

    bool Read( const char * config_file );

    phxrpc::HshaServerConfig & GetHshaServerConfig();

private:
    phxrpc::HshaServerConfig ep_server_config_;
};
