/* allocsvr_tool_impl.h

 Generated by phxrpc_pb2tool from allocsvr.proto

*/

#pragma once

#include <stdio.h>

#include "phxrpc_allocsvr_tool.h"
namespace phxrpc {
    class OptMap;
}

class AllocsvrToolImpl : public AllocsvrTool
{
public:
    AllocsvrToolImpl();
    virtual ~AllocsvrToolImpl();

    virtual int PHXEcho( phxrpc::OptMap & opt_map );

    virtual int GetSeq( phxrpc::OptMap & opt_map );

};

