/* allocsvr_client.h

 Generated by phxrpc_pb2client from allocsvr.proto

*/

#pragma once

#include "allocsvr.pb.h"
#include "phxrpc/rpc.h"

class AllocsvrClient
{
public:
    static bool Init( const char * config_file );

    static const char * GetPackageName();

public:
    AllocsvrClient();
    ~AllocsvrClient();

    int PHXEcho( const google::protobuf::StringValue & req,
        google::protobuf::StringValue * resp );

    int PhxBatchEcho( const google::protobuf::StringValue & req,
        google::protobuf::StringValue * resp );

    int GetSeq( const allocsvr::SeqReq & req,
        allocsvr::SeqResp * resp );


};
