/* allocsvr_server_config.cpp

 Generated by phxrpc_pb2server from allocsvr.proto

*/

#include "allocsvr.pb.h"
#include "allocsvr_server_config.h"

AllocsvrServerConfig :: AllocsvrServerConfig()
{
}

AllocsvrServerConfig :: ~AllocsvrServerConfig()
{
}

bool AllocsvrServerConfig :: Read( const char * config_file )
{
    bool ret = ep_server_config_.Read( config_file );

    if ( strlen( ep_server_config_.GetPackageName() ) == 0 ) {
        ep_server_config_.SetPackageName( 
allocsvr::SeqReq::default_instance().GetDescriptor()->file()->package().c_str() );
    }

    return ret;
}

phxrpc::HshaServerConfig & AllocsvrServerConfig :: GetHshaServerConfig()
{
    return ep_server_config_;
}
