/* allocsvr_tool_impl.cpp

 Generated by phxrpc_pb2tool from allocsvr.proto

*/

#include "allocsvr_tool_impl.h"
#include "allocsvr_client.h"

#include "phxrpc/file.h"

using namespace phxrpc;

AllocsvrToolImpl:: AllocsvrToolImpl()
{
}

AllocsvrToolImpl:: ~AllocsvrToolImpl()
{
}

int AllocsvrToolImpl :: PHXEcho( phxrpc::OptMap & opt_map )
{
    google::protobuf::StringValue req;
    google::protobuf::StringValue resp;

    if( NULL == opt_map.Get( 's' ) ) return -1;

    req.set_value( opt_map.Get( 's' ) );

    AllocsvrClient client;
    int ret = client.PHXEcho( req, &resp );
    printf( "%s return %d\n", __func__, ret );
    printf( "resp: {\n%s}\n", resp.DebugString().c_str() );

    return ret;
}

int AllocsvrToolImpl :: GetSeq( phxrpc::OptMap & opt_map )
{
    allocsvr::SeqReq req;
    allocsvr::SeqResp resp;

    //TODO: fill req from opt_map


    AllocsvrClient client;
    int ret = client.GetSeq( req, &resp );
    printf( "%s return %d\n", __func__, ret );
    printf( "resp: {\n%s}\n", resp.DebugString().c_str() );

    return ret;
}

