/* phxrpc_allocsvr_tool.cpp

 Generated by phxrpc_pb2tool from allocsvr.proto

 Please DO NOT edit unless you know exactly what you are doing.

*/

#include "phxrpc/file.h"

#include "phxrpc_allocsvr_tool.h"
#include "allocsvr_client.h"

using namespace phxrpc;

AllocsvrTool :: AllocsvrTool()
{
}

AllocsvrTool :: ~AllocsvrTool()
{
}

int AllocsvrTool :: PHXEcho( phxrpc::OptMap & /* opt_map */ )
{
   printf( "\n    *** PHXEcho unimplement ***\n" );

    return -1;
}

int AllocsvrTool :: GetSeq( phxrpc::OptMap & /* opt_map */ )
{
   printf( "\n    *** GetSeq unimplement ***\n" );

    return -1;
}


