/* phxrpc_allocsvr_stub.h

 Generated by phxrpc_pb2client from allocsvr.proto

 Please DO NOT edit unless you know exactly what you are doing.

*/

#pragma once

#include "allocsvr.pb.h"

namespace phxrpc {
    class BaseTcpStream;
    class ClientMonitor;
}

class AllocsvrStub
{
public:
    AllocsvrStub( phxrpc::BaseTcpStream & socket, phxrpc::ClientMonitor & client_monitor );
    ~AllocsvrStub();

    void SetKeepAlive( const bool keep_alive );

    int PHXEcho( const google::protobuf::StringValue & req,
        google::protobuf::StringValue * resp );

    int GetSeq( const allocsvr::SeqReq & req,
        allocsvr::SeqResp * resp );

private:
    phxrpc::BaseTcpStream & socket_;
    phxrpc::ClientMonitor & client_monitor_;
    bool keep_alive_;
};

