/* phxrpc_allocsvr_service.h

 Generated by phxrpc_pb2service from allocsvr.proto

 Please DO NOT edit unless you know exactly what you are doing.

*/

#pragma once

#include "allocsvr.pb.h"

class AllocsvrService
{
public:
    AllocsvrService();
    virtual ~AllocsvrService();

    virtual int PHXEcho( const google::protobuf::StringValue & req,
        google::protobuf::StringValue * resp );

    virtual int GetSeq( const allocsvr::SeqReq & req,
        allocsvr::SeqResp * resp );

};

