/* phxrpc_allocsvr_dispatcher.h

 Generated by phxrpc_pb2service from allocsvr.proto

 Please DO NOT edit unless you know exactly what you are doing.

*/

#pragma once

#include "phxrpc/http.h"
#include "phxrpc/rpc.h"

class AllocsvrService;

class AllocsvrDispatcher
{
public:
    AllocsvrDispatcher( AllocsvrService & service, phxrpc::DispatcherArgs_t * dispatcher_args );

    ~AllocsvrDispatcher();

    int PHXEcho( const phxrpc::HttpRequest & request, phxrpc::HttpResponse * response );

    int GetSeq( const phxrpc::HttpRequest & request, phxrpc::HttpResponse * response );

private:
    AllocsvrService & service_;
    phxrpc::DispatcherArgs_t * dispatcher_args_;

public:
    static const phxrpc::HttpDispatcher< AllocsvrDispatcher >::URIFuncMap & GetURIFuncMap();

};

